# Generated by Django 2.0.6 on 2019-09-24 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_mysiteuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('userFullName', models.CharField(default='', max_length=200)),
                ('userEmail', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(default='', max_length=200)),
                ('userMobile', models.BigIntegerField()),
                ('image', models.CharField(default='', max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.UserRole')),
            ],
        ),
    ]
