# Generated by Django 2.0.6 on 2019-09-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysiteuser',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
