# Generated by Django 2.0.6 on 2019-09-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_mysiteuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysiteuser',
            old_name='image',
            new_name='userImage',
        ),
    ]
